def _PLATFORM = project.properties.get('buildPlatform')
assert (_PLATFORM == 'android' || _PLATFORM == 'netty' || _PLATFORM == null)

if (_PLATFORM == null) {
    _PLATFORM = 'android'
}

project.ext {
    PLATFORM = _PLATFORM
    IS_ANDROID = _PLATFORM == 'android'
    IS_NETTY = _PLATFORM == 'netty'
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    // Android specific dependencies.
    if (project.properties.get('buildPlatform', 'android') == 'android') {
        dependencies {
            classpath 'com.android.tools.build:gradle:8.7.3'
        }
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // Alternative repository for Web3j
        maven { url "https://artifacts.consensys.net/public/maven/maven/" }
    }
}
