apply plugin: project.IS_ANDROID ? 'com.android.application' : 'application'

if (project.IS_ANDROID) {
    android {
        defaultConfig {
            namespace = "io.crossbar.autobahn.demogallery"
            compileSdkVersion 35
            minSdkVersion 23
            targetSdkVersion 36
            multiDexEnabled true
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            }
        }
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
        sourceSets {
            main {
                java {
                    include 'io/crossbar/autobahn/demogallery/android/**'
                    include 'io/crossbar/autobahn/demogallery/ExampleClient.java'
                    exclude 'io/crossbar/autobahn/demogallery/netty/**'
                }
            }
        }
        packaging {
            resources {
                excludes += [
                    'META-INF/spring.tooling',
                    'META-INF/spring.handlers',
                    'META-INF/spring.schemas',
                    'META-INF/license.txt',
                    'META-INF/notice.txt',
                    'META-INF/INDEX.list'
                ]
            }
        }
    }

    dependencies {
        implementation project(path: ':autobahn')
        implementation 'androidx.appcompat:appcompat:1.7.1'
        implementation 'com.android.support:multidex:1.0.3'
        implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
        implementation 'com.google.android.material:material:1.13.0'
        implementation 'com.basgeekball:awesome-validation:4.3'
        implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
    }
} else {
    // Netty build
    application {
        mainClass = 'io.crossbar.autobahn.demogallery.netty.Main'
    }
    
    dependencies {
        implementation project(path: ':autobahn')
    }
    
    sourceSets {
        main {
            java {
                include 'io/crossbar/autobahn/demogallery/netty/**'
                include 'io/crossbar/autobahn/demogallery/ExampleClient.java'
                include 'io/crossbar/autobahn/demogallery/data/**'
                exclude 'io/crossbar/autobahn/demogallery/android/**'
            }
        }
    }
    
    jar {
        version = project.properties.get("buildVersion", "")
    }

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
