name: Build the Project

on:
  push:
    branches:
       - master
  pull_request:
    branches:
       - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run unit tests with coverage
        run: ./gradlew :autobahn:testDebugUnitTest :autobahn:jacocoTestReport

      - name: Build android library
        run: ./gradlew :autobahn:build

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            autobahn/build/reports/tests/
            autobahn/build/test-results/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: autobahn/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          fail_ci_if_error: false
          verbose: true

      - name: Build Docker image for integration tests
        run: docker build -t autobahn-java:netty -f docker/Dockerfile.netty --build-arg AUTOBAHN_JAVA_VERSION=test .

      - name: Setup Crossbar (for integration tests)
        run: |
          docker run -d -p 8080:8080 --name crossbar crossbario/crossbar
          docker run -d --link crossbar -v ${PWD}/demo-gallery/python:/test crossbario/autobahn-python python -u /test/test_component2.py

      - name: Run integration tests
        timeout-minutes: 2
        run: |
          docker run --rm -i --link crossbar -v ${PWD}:/workspace autobahn-java:netty /bin/bash -c \
            "gradle :demo-gallery:clean :demo-gallery:installDist -PbuildPlatform=netty && \
             /workspace/demo-gallery/build/install/demo-gallery/bin/integration-test ws://crossbar:8080/ws realm1"
